title: JoCee Holladay
email: joceeporter@gmail.com
port: 4001
description: >- # this means to ignore newlines until "baseurl:"
 A place to share my Technology Projects, Finance research, nonprofit experience, business development and everything in between.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jocee.porter
github_username: jjoocceeee
instagram_username: jocee.holladay
# Build settings

markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
# collections_dir: collections
collections:
  portfolios:
    output: true
    permalink: /:collection/:title
  highlights:
    output: true
    permalink: /:collection/:title
contact_url: https://jadenholladay.herokuapp.com/jocee
maincolor: '#F2CBCB'
secondarycolor: '#F2CBCB'
# remote_theme: jekyll-theme-clean-blog
# theme: jekyll-theme-clean-blog
# sass:
#     sass_dir: ./_sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
